//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infor.HammPdfReading.UnitTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infor.HammPdfReading.UnitTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DACH ROOF TECHO КРЫША.
        /// </summary>
        internal static string designation {
            get {
                return ResourceManager.GetString("designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Teile-Nr. Gültig für Menge Einheit Benennung Designation Denominación Наименование
        ///Item Part No. Valid for Quantity Unit
        ///Posición Referencia Válido para Cantidad Unidad
        ///Позиц
        ///ия
        ///№ детали Действует
        ///для
        ///Количе
        ///ство
        ///Ед.
        ///1 860670 1-9999 1 PC DACH ROOF TECHO КРЫША
        ///2 1210106 1-9999 4 PC SCHEIBE WASHER ARANDELA ПОДКЛАДНАЯ ШАЙБА
        ///3 1213830 1-9999 4 PC ZYLINDERSCHRAUBE CHEESE-HEAD SCREW TORNILLO CILÍNDRICO ВИНТ С ЦИЛИНДРИЧЕСКОЙ
        ///ГОЛОВКОЙ
        ///4 2534259 1-9999 4 PC SICHERUNGSMUTTER SAFETY NUT TUERCA D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string page {
            get {
                return ResourceManager.GetString("page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 860670 1-9999 1 PC DACH ROOF TECHO КРЫША.
        /// </summary>
        internal static string row {
            get {
                return ResourceManager.GetString("row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 860670 1-9999 1 PC DACH ROOF TECHO КРЫША
        ///2 1210106 1-9999 4 PC SCHEIBE WASHER ARANDELA ПОДКЛАДНАЯ ШАЙБА.
        /// </summary>
        internal static string rows {
            get {
                return ResourceManager.GetString("rows", resourceCulture);
            }
        }
    }
}
