//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infor.HammPdfReading.UnitTest.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infor.HammPdfReading.UnitTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Position Teile-Nr. Gültig für Menge Einheit Benennung Designation Denominación Наименование
        ///Item Part No. Valid for Quantity Unit
        ///Posición Referencia Válido para Cantidad Unidad
        ///Позиц
        ///ия
        ///№ детали Действует
        ///для
        ///Количе
        ///ство
        ///Ед.
        ///1 860670 1-9999 1 PC DACH ROOF TECHO КРЫША
        ///2 1210106 1-9999 4 PC SCHEIBE WASHER ARANDELA ПОДКЛАДНАЯ ШАЙБА
        ///3 1213830 1-9999 4 PC ZYLINDERSCHRAUBE CHEESE-HEAD SCREW TORNILLO CILÍNDRICO ВИНТ С ЦИЛИНДРИЧЕСКОЙ
        ///ГОЛОВКОЙ
        ///4 2534259 1-9999 4 PC SICHERUNGSMUTTER SAFETY NUT TUERCA D [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string page {
            get {
                return ResourceManager.GetString("page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 860670 1-9999 1 PC DACH ROOF TECHO КРЫША.
        /// </summary>
        internal static string row {
            get {
                return ResourceManager.GetString("row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 860670 1-9999 1 PC DACH ROOF TECHO КРЫША
        ///2 1210106 1-9999 4 PC SCHEIBE WASHER ARANDELA ПОДКЛАДНАЯ ШАЙБА.
        /// </summary>
        internal static string rows {
            get {
                return ResourceManager.GetString("rows", resourceCulture);
            }
        }
    }
}
